name: Deploy to GitHub Pages

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            pages: write
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            # - name: Set up Node.js
            #   uses: actions/setup-node@v2
            #   with:
            #     node-version: '14'

            # - name: Install dependencies
            #   run: npm install

            # - name: Build
            #   run: npm run build

            - name: "upload"
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./test/

            - id: deploy
              name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
              with:
                  token: ${{ github.token }}
